version: 2
jobs:
  validate_terraform:
    docker:
      - image: hashicorp/terraform:light
        environment:
          DIGITALOCEAN_TOKEN: mocked
    steps:
      - checkout
      - run: terraform init
      - run: "[ -z \"$(terraform fmt -write=false)\" ] || { terraform fmt -write=false -diff; exit 1; }"
      - run: terraform validate

workflows:
  version: 2
  deploy:
    jobs:
      - validate_terraform
